### ISSUE TITLE
replace the activator with something less dumb

### ISSUE THREAD

**Issue by thecatontheceiling** [luke-beep/guide-to-optimizing-windows#8]
**Is your feature request related to a problem? Please describe.**
doesn't work on home edition, switches edition to pro from education, enterprise, etc. and will require reactivating every 180 days. also doesnt persist after reinstalling windows and some online features do not work.

**Describe the solution you'd like**
just direct users to MAS (Microsoft Activation Scripts), very high quality HWID activator that supports all windows editions, office, etc.

**Comment by luke-beep** [comment]
This repository is mostly for myself. I only use pro therefore I don't need to add other versions, but sure.

**Comment by luke-beep** [comment]
Done.
